version: '3'

services:
    app:
        build: .
        command: npm run dev
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
        networks:
            - app-network
    db:
        image: mysql:5.7
        restart: always
        tty: false
        volumes:
            - ./.docker/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge